---
title: "Türkiye'de Alınan Verilen Göçlerin İllere Dağılımı-Cinsiyet-Yaş-Uyruk İncelemesi "
author: 
  - Selin Ertürk[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 21080351, [Github Repo](https://github.com/selinerturk/Vize)


# Giriş
 Göç insanların doğal, ekonomik, sosyal ve siyasal nedenlerden dolayı sürekli yaşadığı yerlerden başka yerlere toplu olarak veya bireysel olarak yerleşmeleri olayına denir.Bu yerleşim ülke içinde veya ülkeler arası olabilir. Her ikisinin ana sebebi de mevcut şartlardan daha iyi olan şartlara sahip bir hayata geçmektir.   Bu şartlar detaylı bir bakış açısıyla değerlendirildiğinde ülkenin durumu hakkında önemli bilgileri bize sunar. Dışa göç verme oranları artan bir ülkenin şartlarında olumsuz gelişen durumlar olduğunu söylemek yanlış olmaz. Aynı şekilde dışardan göç alan bir ülke içinde diğer ülkelerden daha gelişmiş şartlara sahip olduğunu söyleyebiliriz. Göç genel olarak olumlu olumsuz olarak yorum yapabilirken arka planda yarattığı etkilerin de göz önünde bulundurulması gereken bir kavramdır. Çünkü göçün yarattığı bu mekansal değişim aynı zamanda birey, toplum ve milletlerin anlam ve değer dünyasının değişimi ve dönüşümünü de ifade etmektedir. Bu değişim ve dönüşümle beraber terk edilen ve yerleşilen yeni mekânla birlikte yeni mekânlardaki insanlar, değerler, kültürler ve insan ile ilgili ne varsa etkilenir.Ülkenin verdiği ve aldığı göçler olumlu olumsuz bir çok yansımayla karşılacaktır.

## Çalışmanın Amacı
 Veri setim 2018-2019 yılları arsında Türkiye'de görülen dış göçlerin illere göre dağılımını,yaş aralıkları ve cinsiyet ve bireylerin Türk uyruklu ve yabancı uyruklu olması durumunu içermektedir.Çalışmamın amacı ;

1. Bu iki yıl esas alınarak dış göçün en çok etki ettiği iller hangileridir ve bu etkinin sebep sonuçları nasıl değerlendirmelidir? 2.Göçlerde etkili olan yaş grupları nelerdir ve bununla ilgili alınması gereken önlemler nelerdir? 
3.Göçlerde etkili olan cinsiyetler ve toplumdaki yeri nedir?
4.Alınan ve verilen göçlerle birlikte ortaya çıkan nüfus değişikliği nasıl değerlendirilmelidir? 
 
 Analizde ortaya koymak istediğim, tüm bu değişkenlerle birlikte göçün ortaya çıkardığı sonuçları temellere dayandırarak nasıl değerlendirmek gerekir,ne gibi politikalar izlemek gerekir sorularını yantlamaktır.

## Literatür 

###Kadınlar
 
 Mevcut göç akımlarıyla ilgili yenilikler, kadın göçmenlerin giderek görünür olması, kadınların göç hareketlerine artık bir aile bireyi olarak değil, tek başına hareket eden göçmenler olarak katılmaları ve sınırlar ötesine hareket etmeleridir. Kadınların göç süreçlerinin önemli aktörleri haline gelmesi hem göçün feminizasyonu hem de buna paralel olarak meydana gelen işgücü piyasasının feminizasyonu ile birlikte ortaya çıkmıştır..Son yıllarda bilimde cinsiyet eşitliğine yönelik önemli ilerlemeler kaydedilmesine rağmen, kadın araştırmacılar akademik işgücü piyasasında önemli engellerle karşılaşmaya devam ediyor. Uluslararası hareketlilik, bilim insanlarının profesyonel ağlarını genişletmeleri için bir strateji olarak giderek daha fazla kabul görmektedir ve bu, akademik kariyerlerdeki cinsiyet farkını daraltmaya yardımcı olabilir.Akademide cinsiyet eşitliğini teşvik eden çok çeşitli programlar başlatılmış olsa da, cinsiyet eşitsizlikleri akademi ve bilimlerin neredeyse tüm yönlerinde devam etmektedir.[zhao2023gender] Bu iki durumdan ortak çıkacak durum ise göçlerde kadın nüfusunun artmasına karşılık bu artışın yönetiminin eksik kalınan bir durum olmasıdır.Bu sorunun çözümü için atılacak ilk adım ülke genelinde kadın göçmenlerin yoğun olduğu şehirlerin ve eğitim-iş alanlarında etkin yaş gruplarına yönelik bir tespitin devamında eğitimlerini daha nitelikli bir hale getirecek çalışmalar yapılmalı ve bununla beraber ülkede hem kadın haklarına hem eğitime bir ivme kazandırılmalıdır.
 
###Aile yapısı ve uyum
 
 Ailelerin parçalanma sebeplerinden birisi de iç ve dış göçlerdir. Göç olgusu, tarih boyunca toplumların ve bireylerin yaşamını ekonomik, siyasal, kültürel, sosyal ve psikolojik olarak çok yönlü ve karmaşık bir şekilde etkilemiştir. Özellikle imkânların yeterli olmadığı yerlerde yaşayan bireyler, yurt içinde ya da yurt dışına göç etmek zorunda kalmışlardır. Ebeveynlerin işgücü amaçlı olarak başka yerlere göç etmesi, ailenin parçalanması ve aile bireylerinin birbirinden ayrı düşmesi ile sonuçlanabilmektedir. Anne ya da babanın uzun zaman aileden ayrı kalması, aile içinde meydana gelen hastalıklar ve ölümler, kişilerin sosyal, duygusal durumlarına ve bireyler arası iletişime zarar vererek aile sağlığını olumsuz şekilde etkilemektedir.[adem2014dics]Bu sorunlar beraberinde bireylerin iç dünyasında sıkıntılara yol açmakta ve sorunlar toplumda huzursuzlukla sonuçlanmaktadır.Asıl sebep bireylerin hayat şartlarında yaşadığı değişikliğe karşı yaşadığu uyumsuzluktan kaynaklanmaktadır.[@csimcsek2018turkiye] Huzursuzluğun önüne geçmek ise göç konusunda önemli amaçlardan biri olmalıdır.Toplumun genelinde huzur ortamının sağlanması aile yapısının sağlam şekilde devam etmesini sağlamaktır.Bunun için öncelik dışa verilen göçlerin sebeplerinin çözümüne kavuşturularak ailelerin şartlarının ülke içinde bütünlük dahilinde düzeltirek dağılmanın önüne geçmektir.ikinci olarak ise dış göç ile ülkeye gelmiş olan yabancı uyruklu kişilerin ülke şartalarına zıt davranışlar sergileyerek huzursuzluk yaratma durumlarının önüne geçerek gelen dış göçün etkili olduğu illere kurulan dil-kültür gibi konuların bireylere aktarılmasını sağlayavak kurumlar ile baraber hem gelen bireylerin uyumsuzlukla daha iyi mücadele etmesi sağlanmalı hemde ülkenin genel düzeninde meydana gelecek bozulmaların önüne geçilmiş olunmalıdır. 
 
 
###Sağlık
 Nüfus artışı, günümüzün en önemli çevre sorunlarından birisidir. İçme ve kullanma suyu, gürültü, hava kirliliği, radyasyon ve atıklar gibi pek çok çevre sağlığı konusunda nüfus artışıyla birlikte sorunlar yaşanabilir. Nüfus artışına yol açan en önemli etmenlerden biri ise göçlerdir.Özellikle büyük şehirlerde nüfus artışına neden olan göçler işsizlik, eğitim, barınma, çevre ve alt yapı sorunlarıyla beraber sağlık sorunlarını da beraberinde getirmektedir. Göç alan bölgelerde yeterli sağlık kuruluşunun olmaması, göçmenlerin düşük gelir düzeyi, sağlık sigortalarının olmaması, dil sorunu, aynı hanede çok sayıda ailenin yaşaması, yaşanan olağanüstü duruma ve şiddete bağlı gelişen ruhsal bozukluklar, beslenme ve hijyen sorunları, temiz içme suyu sağlanamaması ve atıkların uzaklaştırılamaması gibi faktörler de göç eden bireylerin sağlık koşullarını olumsuz yönde etkiler.Tüm olumsuz faktörler işsizlik ve yoksullukla beraber hastalık patlamasına neden olmaktadır ve günümüzde sorun olmayan hastalıklar yeniden sorun olmaya başlamaktadır. [@aydougan2017turkiye] [@fofana2023cross] Nüfusu aldığı göçlerle beraber yoğunlaşan illerde ülkeye giriş ve çıkışlarda gerekli sağlık taramaları yapılmalı yayılma riski olan hastalıkların tedavisi sağlamdıktan sonra giriş ve çıkışlara izin verilmedir.Bunun için göçün olduğu illere gerekli sağlık kuruluşları kurulmalı ve denetlemeleri sağlanmalıdır.
 
###Ekonomi
 Çağdaş göç teorilerinin başlangıcı olarak görülen neo-klasik yaklaşımın merkezinde de itme-çekme yaklaşımı yer almaktadır. Neo-klasik yaklaşımda göç mikro ve makro düzeyde açıklanmıştır. Makro düzeyde göç, üretim faktörlerinin ülkeler arası dağılımındaki eşitsizlikten kaynaklanmakta ve göç hareketleri emeğin bol ve dolayısıyla ücretlerin düşük olduğu ülkelerden emeğin kıt ve ücretlerin yüksek olduğu ülkelere doğru gerçekleşmektedir.Mikro düzeyde ise göç, göç etme ve etmemenin avantaj ve dezavantajlarına ilişkin tam bilgiye sahip rasyonel bireyler tarafından verilen kararlarının sonucu gerçekleşmektedir.Özetle fayda maksimizasyonu, rasyonel seçim, bölge ve ülkeler arası faktör-fiyat farklılıkları ve işgücü hareketliliği ilkelerine dayanan neo-klasik ekonomi paradigmasını yansıtan itme-çekme modellerine göre, göçün başlıca nedeni ekonomiktir. [leblang2023ties] Hayatın yürütülmesini sağlayan temel konu ekonomidir.Hayat şartları ekonomik düzeyin izin verdiği ölçüde iyileştirilebilir.Verilen dış göçün önüne geçmek için sağlanması gereken şart hayat şartlarını iyileştirmeye yöelik bir ekonominin sağlanmış olmasıdır.Bu temelde bireylere sağlanan iş imkanları ile berbaber ülkede yürütülen ekonomi politikalarının bireylere olumlu  yansımasını gerektirir.Bu sebeple göç veren illerin göç alan illerle karşılaştırılarak şartların iyileştirilmesi sağlanmalıdır.Nüfusun ülke genelide eşit dağılımını sağlayacak bir ekonomi politikası yürütülmelidir.
 
 


\newpage
# Kaynakça {#references}
<div id="refs"></div>

